

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    volumes:
      - .:/var/www

    depends_on:
      - postgres
      - mailhog
    ports:
      - 8000:8000

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
